name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        architecture: [amd64, 'arm', arm64]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/scuroguardiano/mikrotikexporter:${{ matrix.architecture }}
          platforms: linux/${{ matrix.architecture }}
  
  merge:
    runs-on: ubuntu-latest
    needs: docker
    
    steps:
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/scuroguardiano/mikrotikexporter:latest \
            ghcr.io/scuroguardiano/mikrotikexporter:amd64 \
            ghcr.io/scuroguardiano/mikrotikexporter:arm64 \
            ghcr.io/scuroguardiano/mikrotikexporter:arm
